services:
  postgres-catalogo:
    image: postgres:16
    container_name: catalogo_db_container
    environment:
      POSTGRES_USER: candela
      POSTGRES_PASSWORD: catalogo2026
      POSTGRES_DB: catalogo_db
    ports:
      - "5433:5432"
    restart: always